DROP DATABASE IF EXISTS `courseSelect`;

CREATE DATABASE `courseSelect`;

CREATE TABLE `major`(
`majorId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '专业id',
`majorName` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '无' COMMENT '专业名称',
PRIMARY KEY (`majorId`) USING BTREE
)ENGINE = INNODB AUTO_INCREMENT = 5 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `grade`(
`gradeId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '年级id',
`gradeName` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '无' COMMENT '年级名称',
PRIMARY KEY (`gradeId`) USING BTREE
)ENGINE = INNODB AUTO_INCREMENT = 5 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `class`(
`classId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '班级id',
`className` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '无' COMMENT '班级名称',
PRIMARY KEY (`classId`) USING BTREE
)ENGINE = INNODB AUTO_INCREMENT = 5 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `student`(
`studentId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '学生id',
`studentName` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '无' COMMENT '学生名称',
`studentPwd` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '无' COMMENT '学生密码',
`majorId` INT(11) NOT NULL DEFAULT 0 COMMENT '所属专业id',
`gradeId` INT(11) NOT NULL DEFAULT 0 COMMENT '所属年级id',
`classId` INT(11) NOT NULL DEFAULT 0 COMMENT '所属班级id',
PRIMARY KEY (`studentId`) USING BTREE
)ENGINE = INNODB AUTO_INCREMENT = 5 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `teacher`(
`teacherId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '管理员id',
`teacherName` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '无' COMMENT '管理员姓名',
`teacherPwd` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '无' COMMENT '管理员密码',
`majorId` INT(11) NOT NULL DEFAULT 0 COMMENT '所在专业id',
PRIMARY KEY (`teacherId`) USING BTREE
)ENGINE = INNODB AUTO_INCREMENT = 5 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `course`(
`courseId` INT(11) NOT NULL AUTO_INCREMENT COMMENT '课程id',
`courseName` VARCHAR(64) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL DEFAULT '无' COMMENT '课程名称',
`gradeId` INT(11) NOT NULL DEFAULT 0 COMMENT '开课年级id',
`teacherId` INT(11) NOT NULL DEFAULT 0 COMMENT '开课老师id',
`studentId` INT(11) NOT NULL DEFAULT 0 COMMENT '选课学生id',
`startTime` DATETIME COMMENT '开始选课日期',
`finishTime` DATETIME COMMENT '结束选课日期',
`stuNum` INT(11) NOT NULL DEFAULT 0 COMMENT '课程学生数量',
PRIMARY KEY (`courseId`) USING BTREE
)ENGINE = INNODB AUTO_INCREMENT = 5 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;

CREATE TABLE `choose`(
`studentId` INT(11) NOT NULL DEFAULT 0 COMMENT '学生id',
`cousrseId` INT(11) NOT NULL DEFAULT 0 COMMENT '课程id'
)ENGINE = INNODB AUTO_INCREMENT = 5 CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = DYNAMIC;
